version: '3'

services:
  webserver:
    build: ./docker/webserver
    image: docker_template_web
    # Change template to your project name as this name could be used to access container.
    container_name: template_webserver
    # Change external ports for every project.
    ports:
      - "8011:80"
      - "44311:443"
    environment:
        PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
        XDEBUG_CONFIG: remote_host=172.19.0.1
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    # Change template to your project name as this name could be used to access container.
    container_name: template_database
    # Change external ports for every project.
    # Disable mysql port if no GUI client used.
    ports: 
      - "3311:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/egame.cnf
    # Change environment values to something custom to add more security.
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_template
      # User and Password should match values in my.cnf file.
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=pass4a4gr123

networks:
  default:
    external:
      name: devdocker_standard
