version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: docker_template_web
    container_name: template_webserver
    ports:
      - "80:80"
      - "443:443"
    environment:
        PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
        XDEBUG_CONFIG: remote_host=172.19.0.1
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/egame.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_template
      # User and Password should match values in my.cnf file.
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=pass4a4gr123
